name: Lint
on:
  pull_request:
    branches: [ master, staging ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: [12.x]
      - run: npm install -D eslint
      - run: npx eslint js/